clear;
close all;
M=8;
N=500;
SNR_dB=10;
dataSymbols=randi([0 M-1],N,1);
txSignal=pskmod(dataSymbols,M);
rxSignal=awgn(txSignal,SNR_dB,'measured');
demodulatedSymbols=pskdemod(rxSignal,M);
numErrors=sum(dataSymbols ~=demodulatedSymbols);
SER=numErrors/N;
fprintf('M-PSK MODUATION ORDER(M): %d\n',M);
fprintf('NUMBER OF SYMBOLS: %d\n',N);
fprintf('SNR(dB): %.2f\n',SNR_dB);
fprintf('Calculated Symbol Error Rate(SER): %.4f\n',SER);
figure;
subplot(2,1,1);
plot(real(txSignal),imag(txSignal),'o');
title('Transmitted singnal constellation');
xlabel('In-Phase');
ylabel('quadrature');
grid on;
axis equal;
subplot(2,1,2);
plot(real(rxSignal),imag(rxSignal),'o');
title('recieved signal constellation with AWGN');
xlabel('in-phase');
ylabel('Quadrature');
grid on;
axis equal;